version: 2.1

orbs:
  vr: kohirens/version-release@dev:47392fd6c953c179d49c85cc1fbc449e93f98322

parameters:
  ctx_auto_release:
    default: kohirens-automation
    description: Secrets context
    type: string
  ssh_finger:
    description: SSH fingerprint.
    type: string
    default: "SHA256:TvHHGniDqNTc+a7nHmuYKa1SOt/ru9XE0yueq4MarbY"
  triggered_by_bot:
    default: false
    description: Trigger publishing a release tag workflow.
    type: boolean
  triggered_flow:
    default: "workflow-selector"
    description: Workflow to be executed.
    type: string

executors:
  go:
    docker:
      - image: cimg/go:1.23

jobs:
  co:
    executor: go
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.mod" }}
      - run:
          name: Install Dependencies
          command: go mod tidy
      - save_cache:
          key: go-mod-v1-{{ checksum "go.mod" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: .
          paths: [ . ]

  run-test:
    executor: go
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Unit test"
          command: |
            go test -v

workflows:
  pull-request:
    jobs:
      - co:
          filters: { branches: { ignore: /main|auto-update-changelog/ } }
      - run-test:
          requires: [ co ]

  workflow-selector:
    when:
      and:
        - equal: ["workflow-selector", << pipeline.parameters.triggered_flow >>]
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - vr/workflow-selector:
          context: << pipeline.parameters.ctx_auto_release >>
          ssh_finger: << pipeline.parameters.ssh_finger >>

  publish-changelog:
    when:
      and:
        - equal: ["publish-changelog", << pipeline.parameters.triggered_flow >>]
    jobs:
      - vr/publish-changelog:
          context: << pipeline.parameters.ctx_auto_release >>
          ssh_finger: << pipeline.parameters.ssh_finger >>

  publish-release-tag:
    when:
      and:
        - equal: ["publish-release-tag", << pipeline.parameters.triggered_flow >>]
    jobs:
      - vr/tag-and-release:
          context: << pipeline.parameters.ctx_auto_release >>
